name: rhythmai
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - brotlicffi=1.0.9.2=py310h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.10.5=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - cpuonly=2.0=0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py310hca03da5_0
  - freetype=2.13.3=h47d26ad_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=py310hca03da5_0
  - numpy=2.2.6=py310h4d83441_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.5.4=h5503f6c_0
  - pandas=2.3.3=py310h25f4b65_1
  - pillow=11.1.0=py310h41ba818_1
  - pip=25.2=pyhc872135_1
  - pycparser=2.23=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.15=hdce6c4c_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.2.2=py3.10_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h80987f9_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py310hca03da5_1
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - sympy=1.14.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.2.2=py310_cpu
  - torchvision=0.17.2=py310_cpu
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - blinker==1.9.0
      - build==1.3.0
      - cachetools==6.2.1
      - chromadb==1.3.4
      - click==8.3.0
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - durationpy==0.10
      - exceptiongroup==1.3.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - langchain==1.0.3
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.3
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.2
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.2
      - langgraph-sdk==0.2.9
      - langsmith==0.4.41
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.2.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.10.2
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - packaging==25.0
      - posthog==5.4.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dotenv==1.2.1
      - redis==7.0.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - spotipy==2.25.1
      - sqlalchemy==2.0.44
      - streamlit==1.51.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/rhythmai
